"""
fslab/utils/state.py
====================
[CLI-05] Maintains a hidden ``.fslab/`` directory in the project root that
         stores the build hash and other orchestration metadata.
[CLI-06] Computes a combined SHA256 of ``fslab.yaml`` and every
         ``registry.yaml`` file that was loaded during Two-Pass parsing.
[CLI-07] Compares the freshly-computed hash against the value stored in
         ``.fslab/state.json``.  If they match, generation is skipped unless
         the caller passed ``--force``.

Public API
----------
    StateManager(project_root)
        Context object for all state operations.

    StateManager.compute_config_hash(yaml_path, registry_paths) -> str
        SHA256 hex-digest of all input files concatenated in sorted order.

    StateManager.is_generation_needed(hash) -> bool
        True  → hash changed   (or state file absent)  → must regenerate
        False → hash unchanged → safe to skip

    StateManager.check_user_modifications(render_plan) -> tuple[bool, dict]
        Checks previously generated files to see if the user modified or 
        deleted them before a forced overwrite occurs.

    StateManager.compute_generated_files_state(render_plan) -> dict
        Computes hashes for freshly rendered files to be stored in state.

    StateManager.save(config_hash, generated_files, extra_meta)
        Persist the config hash, generated file hashes, and metadata to 
        ``.fslab/state.json``.

    StateManager.load() -> dict
        Load the raw state dict; returns {} if the file doesn't exist yet.
"""

from __future__ import annotations

import hashlib
import json
import time
from pathlib import Path
from typing import Any, Optional

from fslab.utils.display import console, info, warning

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

STATE_DIR_NAME = ".fslab"          # [CLI-05] hidden state directory name
STATE_FILE_NAME = "state.json"     # persisted hash + metadata
LOG_DIR_NAME = "logs"              # used by fslab build


class StateManager:
    """
    [CLI-05, CLI-06, CLI-07] Manages the ``.fslab/`` state directory and the
    idempotency hash used by Smart Generation.

    Parameters
    ----------
    project_root:
        Absolute path to the directory containing ``fslab.yaml``.
        Defaults to the current working directory.
    """

    def __init__(self, project_root: Optional[Path] = None) -> None:
        self.project_root: Path = (project_root or Path.cwd()).resolve()
        self.state_dir: Path = self.project_root / STATE_DIR_NAME
        self.state_file: Path = self.state_dir / STATE_FILE_NAME
        self.log_dir: Path = self.state_dir / LOG_DIR_NAME

    # ------------------------------------------------------------------
    # Directory bootstrap
    # ------------------------------------------------------------------

    def ensure_dirs(self) -> None:
        """
        [CLI-05] Create ``.fslab/`` and ``.fslab/logs/`` if they do not
        already exist.  Called at the start of every command that writes state.
        """
        self.state_dir.mkdir(parents=True, exist_ok=True)
        self.log_dir.mkdir(parents=True, exist_ok=True)

        # Write a .gitignore inside .fslab/ so build logs are not committed
        gitignore = self.state_dir / ".gitignore"
        if not gitignore.exists():
            gitignore.write_text(
                "# Auto-generated by fslab – do not edit\n"
                "*\n"
                "!.gitignore\n"
            )

    # ------------------------------------------------------------------
    # [CLI-06] Hash computation
    # ------------------------------------------------------------------

    def compute_config_hash(
        self,
        fslab_yaml_path: Path,
        registry_yaml_paths: list[Path],
    ) -> str:
        """
        [CLI-06] Compute a combined SHA256 hash of ``fslab.yaml`` and all
        loaded ``registry.yaml`` files.

        Algorithm
        ---------
        1. Build a sorted, deduplicated list of all input file paths.
           Sorting ensures the hash is deterministic regardless of the order
           in which registries were discovered.
        2. For each file, feed ``path_as_string + NUL + file_bytes`` into a
           running SHA256 digest.  Mixing the path into the digest prevents
           two different files with identical content from hashing to the same
           value (which would be a false "no change" result if a file moves).
        3. Return the 64-character lowercase hex digest.

        Parameters
        ----------
        fslab_yaml_path:
            Path to the project's ``fslab.yaml``.
        registry_yaml_paths:
            Ordered list of ``registry.yaml`` paths returned by the parser.

        Returns
        -------
        str
            64-char hex SHA256 digest.

        Raises
        ------
        FileNotFoundError
            If any of the specified files does not exist on disk.
        """
        # Deduplicate + sort for determinism
        all_paths: list[Path] = sorted(
            set([fslab_yaml_path.resolve()] + [p.resolve() for p in registry_yaml_paths])
        )

        digest = hashlib.sha256()

        for path in all_paths:
            if not path.exists():
                raise FileNotFoundError(
                    f"Cannot compute config hash: file not found: {path}"
                )
            # Mix path into digest (see algorithm note above)
            digest.update(str(path).encode("utf-8"))
            digest.update(b"\x00")
            # Mix file contents
            digest.update(path.read_bytes())
            # Separator between files so adjacent files can't "merge"
            digest.update(b"\xff")

        return digest.hexdigest()

    # ------------------------------------------------------------------
    # [CLI-07] Hash comparison (idempotency check)
    # ------------------------------------------------------------------

    def is_generation_needed(self, current_hash: str) -> bool:
        """
        [CLI-07] Return True if code generation must run, False if it can
        be safely skipped.

        Generation is needed when:
        * The ``.fslab/state.json`` file does not exist yet.
        * The stored ``config_hash`` field differs from *current_hash*.

        Generation can be skipped when the stored hash equals *current_hash*
        (caller is responsible for checking the ``--force`` flag separately).

        Parameters
        ----------
        current_hash:
            The freshly-computed SHA256 from ``compute_config_hash``.

        Returns
        -------
        bool
        """
        state = self.load()
        stored_hash = state.get("config_hash", "")

        if not stored_hash:
            return True  # First run – no state file yet

        return stored_hash != current_hash

    # ------------------------------------------------------------------
    # User Modification Checking
    # ------------------------------------------------------------------

    def check_user_modifications(
        self, render_plan: dict[str, Path]
    ) -> tuple[bool, dict[str, dict[str, str]]]:
        """
        Check if the user has modified or deleted any previously bootstrapped
        files before rendering blindly overwrites them.

        Parameters
        ----------
        render_plan:
            Dictionary mapping template keys (e.g., "build.sbt.j2") to their 
            target Path objects.

        Returns
        -------
        tuple[bool, dict[str, dict[str, str]]]
            - bool: True if at least one tracked file was modified or deleted.
            - dict: Details of changed files, keyed by the full string path.
              Example: { 
                  "/path/to/build.sbt": {"status": "modified", "template": "build.sbt.j2"},
                  "/path/to/deleted.cc": {"status": "missing", "template": "driver.cc.j2"} 
              }
        """
        state = self.load()
        stored_files = state.get("generated_files", {})

        has_changes = False
        changes: dict[str, dict[str, str]] = {}

        for template_key, path in render_plan.items():
            # If the template key isn't in state, it's a new file entirely.
            # We don't consider it "modified" since we never generated it before.
            if template_key not in stored_files:
                continue

            stored_data = stored_files[template_key]
            stored_hash = stored_data.get("hash")
            
            resolved_path = path.resolve()
            path_str = str(resolved_path)

            # 1. Check if the file was deleted by the user
            if not resolved_path.exists():
                has_changes = True
                changes[path_str] = {
                    "status": "missing",
                    "template": template_key
                }
                continue

            # 2. Check if the file's binary content was modified
            current_hash = hashlib.sha256(resolved_path.read_bytes()).hexdigest()
            if current_hash != stored_hash:
                has_changes = True
                changes[path_str] = {
                    "status": "modified",
                    "template": template_key
                }

        return has_changes, changes

    def compute_generated_files_state(
        self, render_plan: dict[str, Path]
    ) -> dict[str, dict[str, str]]:
        """
        Computes the file hashes for a render plan to save into state.
        Call this *after* successfully generating the files.
        """
        files_state = {}
        for template_key, path in render_plan.items():
            resolved = path.resolve()
            if resolved.exists():
                files_state[template_key] = {
                    "hash": hashlib.sha256(resolved.read_bytes()).hexdigest(),
                    "path": str(resolved)
                }
        return files_state

    # ------------------------------------------------------------------
    # Persist / load state
    # ------------------------------------------------------------------

    def save(
        self,
        config_hash: str,
        generated_files: Optional[dict[str, dict[str, str]]] = None,
        extra: Optional[dict[str, Any]] = None,
    ) -> None:
        """
        [CLI-06] Persist *config_hash*, *generated_files*, and any *extra* 
        metadata to ``.fslab/state.json``.

        The file is written atomically: we write to a ``*.tmp`` file first
        then rename it so a crash mid-write cannot corrupt the state.

        Parameters
        ----------
        config_hash:
            The SHA256 computed by ``compute_config_hash``.
        generated_files:
            Optional dictionary returned by ``compute_generated_files_state`` 
            mapping template keys to their paths and hashes.
        extra:
            Optional dict merged into the state payload (e.g., last build
            time, the sbt version used, etc.).
        """
        self.ensure_dirs()

        payload: dict[str, Any] = {
            "config_hash": config_hash,
            "saved_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
            "fslab_version": _fslab_version(),
            "generated_files": generated_files or {},
        }
        if extra:
            payload.update(extra)

        tmp = self.state_file.with_suffix(".json.tmp")
        tmp.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
        tmp.replace(self.state_file)  # atomic rename

    def load(self) -> dict[str, Any]:
        """
        Load the raw state dictionary from ``.fslab/state.json``.

        Returns an empty dict if the file does not exist (first run).
        """
        if not self.state_file.exists():
            return {}
        try:
            return json.loads(self.state_file.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError) as exc:
            warning(
                f"Could not read state file ({exc}). "
                "Treating as first run – generation will proceed."
            )
            return {}

    # ------------------------------------------------------------------
    # Convenience: log file path factory
    # ------------------------------------------------------------------

    def log_file(self, name: str) -> Path:
        """
        [CLI-15] Return a timestamped log file path inside ``.fslab/logs/``.

        Example
        -------
            state.log_file("build") → .fslab/logs/build-20240615T143022.log
        """
        self.ensure_dirs()
        ts = time.strftime("%Y%m%dT%H%M%S", time.gmtime())
        return self.log_dir / f"{name}-{ts}.log"

    # ------------------------------------------------------------------
    # Status report (used by verbose commands)
    # ------------------------------------------------------------------

    def print_status(self) -> None:
        """Pretty-print the current state to the console."""
        state = self.load()
        if not state:
            console.print("[dim]No state recorded yet (.fslab/state.json absent).[/]")
            return

        from rich.table import Table

        table = Table(show_header=False, box=None, padding=(0, 2))
        table.add_column(style="dim", no_wrap=True)
        table.add_column(style="white")

        table.add_row("State file", str(self.state_file))
        table.add_row("Config hash", state.get("config_hash", "—")[:16] + "…")
        table.add_row("Saved at", state.get("saved_at", "—"))
        table.add_row("fslab version", state.get("fslab_version", "—"))
        
        gen_files = state.get("generated_files", {})
        table.add_row("Tracked files", str(len(gen_files)))

        console.print(table)


# ---------------------------------------------------------------------------
# Internal helper
# ---------------------------------------------------------------------------

def _fslab_version() -> str:
    try:
        from fslab import __version__
        return __version__
    except ImportError:
        return "unknown"


# ---------------------------------------------------------------------------
# [CLI-06, CLI-07] Convenience top-level function for use inside commands
# ---------------------------------------------------------------------------


def check_and_maybe_skip_generation(
    *,
    fslab_yaml_path: Path,
    registry_yaml_paths: list[Path],
    force: bool = False,
    dry_run: bool = False,
    project_root: Optional[Path] = None,
) -> tuple[bool, str, StateManager]:
    """
    [CLI-06, CLI-07] High-level helper called from ``fslab generate`` and
    ``fslab compile``.

    Returns
    -------
    (should_generate, current_hash, state_manager)

    ``should_generate`` is True  → caller MUST run Jinja2 rendering.
    ``should_generate`` is False → caller SHOULD skip rendering (hash match).

    Even when ``should_generate`` is False the caller must still return the
    StateManager so it can update state after a successful compile.

    Parameters
    ----------
    fslab_yaml_path:
        Path to ``fslab.yaml``.
    registry_yaml_paths:
        List of ``registry.yaml`` paths used by the Two-Pass parser.
    force:
        [CLI-07] If True, always generate regardless of hash.
    dry_run:
        If True, skip all writes (neither generate nor update state).
    project_root:
        Passed to StateManager; defaults to CWD.
    """
    sm = StateManager(project_root)
    sm.ensure_dirs()

    current_hash = sm.compute_config_hash(fslab_yaml_path, registry_yaml_paths)

    if force:
        info("[bold]--force[/] flag set – skipping hash check, regenerating.")
        return True, current_hash, sm

    if dry_run:
        info("[bold]--dry-run[/] mode – no files will be written.")
        # Still report whether generation *would* run
        needed = sm.is_generation_needed(current_hash)
        if needed:
            info("Hash mismatch – generation [italic]would[/] run (dry-run, skipping).")
        else:
            info("Hash match – generation [italic]would[/] be skipped (dry-run).")
        return False, current_hash, sm

    needed = sm.is_generation_needed(current_hash)

    if not needed:
        # [CLI-07] Log the skip message as specified in the requirements
        console.print(
            "[bold cyan]ℹ[/]  Configuration unchanged, skipping generation."
        )

    return needed, current_hash, sm